from . import sale
from . import product_template
from . import res_partner
from . import stock
from . import stock_quant
from . import stock_return_picking
from . import stock_quality
from . import stock_quality_point
from . import stock_quality_template
from . import mail_thread
from . import production_lot
from . import purchase
from . import stock_traceability
from . import ir_actions_report
from . import stock_production_lot_tag
from . import account_move_line
from . import account_partner_ledger
from . import account_move
from . import stock_production_lot
from . import stock_scrap
from . import account_analytic_tag
from . import ir_sequence
from . import account_aged_partner_balance