from . import sale
from . import product_template
from . import res_partner
from . import stock
from . import stock_quant
from . import stock_quality
from . import stock_quality_point
from . import stock_quality_template
from . import mail_thread
from . import production_lot
from . import purchase
from . import stock_traceability
